//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Booking = new HashSet<Booking>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public int FloorId { get; set; }
        public int CategoryId { get; set; }
        public int StatusId { get; set; }
    
        public virtual ICollection<Booking> Booking { get; set; }
        public virtual Category Category { get; set; }
        public virtual Floor Floor { get; set; }
        public virtual Status Status { get; set; }
    }
}
